---
title: "First Knit"
author: "Kimberly Aldana"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended high school at Benjamin Franklin High School located in Los Angeles, California. I graduated in 2018 with my high school degree. If I can compare English to math class, I would say that English is more of an easier class to complete. English class gives you the ability to write whatever you like, while math is more focused on one way to solve equations. The subject I did best would be English class. I passed with a B+ with honors.  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
The computer I have at home is an Apple computer, that I have had for about two years. From a scale from 1-10, I would say my computer skills follow on a 7. I've used computers my whole life, but I'm not a full on expert. The internet connection at my home is extremely great.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
A name I would prefer for my classmates to call me is Kimberly or Kim for short. If my classmates were to maybe call me another name, preferably I would liked to be called Kimbo Slice.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  What I want to achieve in life follows through happiness and be in a financial steady place. A college subject that would give me great interest is an ASL class. A degree that I'm currently on board into achieving is my sociology degree to become a social worker.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
My home country is resonated in Ecuador, which is located in South America on the equator. If I had an opportunity to travel to another foreign country, I would choose Bora Bora. I have not been in the military but I have been thinking about it. If I can choose a branch to be in, I would choose the Marines because I'm more familiar with it due to my best friends involvement. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
 I have not taken Math 115 or Math 116 in my college path until now. A grade that I would love to have in this class would be a B+. I plan to come to office hours and take advantage of tutoring, which will help my chances of passing with a satisfactory grade.  
   
 






  




